# Generated by Django 5.1 on 2025-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=10, unique=True, verbose_name='ID Empleado')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('puesto', models.CharField(choices=[('Chofer', 'Chofer'), ('Administrativo', 'Administrativo'), ('Gerente', 'Gerente'), ('Mantenimiento', 'Mantenimiento'), ('Ventas', 'Ventas')], max_length=20, verbose_name='Puesto')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de Contratación')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
